# Generated by Django 4.1.13 on 2024-03-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0003_department_doctor_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='health_insurance',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
