# Generated by Django 4.2.10 on 2024-04-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0009_department_contact_email_department_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TimeField()),
            ],
        ),
    ]
