# Generated by Django 4.1.13 on 2024-04-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0010_otp'),
        ('patient_app', '0011_fileupload_appointment_form_appointment'),
    ]

    operations = [
    ]
