# Generated by Django 4.1.13 on 2024-04-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0012_merge_20240421_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='appointment_form',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='file',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_content',
            field=models.BinaryField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Appointment_form',
        ),
    ]
