# Generated by Django 4.1.13 on 2024-04-22 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0015_doctor_qualifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.CharField(max_length=255, verbose_name='Available Days')),
                ('time_slot', models.CharField(max_length=200, verbose_name='Available Time')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.doctor', verbose_name='Doctor')),
            ],
        ),
    ]
