# Generated by Django 4.1.13 on 2024-04-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0016_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='max_patient_count',
            field=models.PositiveIntegerField(default=5, verbose_name='Max Patient Count'),
        ),
    ]
