# Generated by Django 4.1.13 on 2024-04-22 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0017_schedule_max_patient_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appid', models.AutoField(primary_key=True, serialize=False)),
                ('appmadeon', models.DateField(auto_now_add=True, verbose_name='Appointment Made Date')),
                ('appdate', models.DateField(verbose_name='Appointment Date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient', to='patient_app.patient')),
            ],
        ),
    ]
